// מאגר המשרדים והארגונים, עם ערוצי פניות הציבור שלהם.
// כל הפרטים נאספו מפרסומים רשמיים (אתרי הגופים, המדריך הממשלתי "לאן לפנות" מ-2024, כל זכות).
// נבדק לאחרונה: אוקטובר 2026. פרטים שלא נמצא להם מקור רשמי עדכני לא הוכנסו.
//
// שדות:
//   form    — קישור לטופס המקוון של פניות הציבור (או לדף הרשמי שמפנה אליו)
//   email   — כתובת מייל רשמית לפניות הציבור
//   postal  — כתובת למשלוח מכתב בדואר
//   site    — אתר הארגון
//   sources — היכן נמצאו הפרטים
//   preferEmail — עדיף לשלוח במייל ולא בטופס (למשל טופס שמיועד לתלונות)
//   formTip — הנחיה קצרה לשליחת מחמאה בערוץ של הגוף
var GUIDE_2024 = "https://www.gov.il/BlobFolder/generalpage/general_tuota/he/Lean_Lifnot_he2.pdf";

window.OFFICES = [
  { group: "משרדי ממשלה ורשויות", items: [
    { id: "btl", formTip: "הטופס מבקש תעודת זהות וקוד. בנושא הפנייה בחרו \"שרות לקוחות\" וכתבו בשורה הראשונה \"מחמאה\". דרך פשוטה יותר: מכתב מודפס שנמסר למנהל/ת הסניף.", name: "המוסד לביטוח לאומי",
      site: "https://www.btl.gov.il",
      form: "https://www.btl.gov.il/About/contact_us/Pages/pniot_hatsibur.aspx",
      postal: "האגף לפניות הציבור, המוסד לביטוח לאומי, רח' יפו 217, ירושלים 9199908",
      sources: ["https://www.btl.gov.il/About/contact_us/Pages/pniot_hatsibur.aspx", GUIDE_2024] },
    { id: "taxes", formTip: "מערכת הפניות המקוונת מבקשת הזדהות. אפשר גם לשלוח מכתב מודפס בדואר או למסור אותו במשרד.", name: "רשות המסים בישראל",
      site: "https://www.gov.il/he/departments/general/ta-contact-us",
      form: "https://secapp.taxes.gov.il/srpniyotcrm/#/newPniya",
      postal: "רשות המסים, שירות לקוחות, רח' בנק ישראל 7, ת\"ד 1170, ירושלים 9195024",
      sources: ["https://go.gov.il/InfoCenter", GUIDE_2024] },
    { id: "population", preferEmail: true, formTip: "הטופס המקוון מיועד בעיקר לתלונות, לכן עדיף לשלוח במייל, או למסור מכתב מודפס למנהל/ת הלשכה.", name: "רשות האוכלוסין וההגירה",
      form: "https://govforms.gov.il/mw/forms/complaint@piba.gov.il",
      email: "tz@piba.gov.il",
      postal: "פניות ותלונות הציבור, רשות האוכלוסין וההגירה, רח' אגריפס 42, ירושלים 9430125",
      sources: [GUIDE_2024, "https://www.gov.il/he/pages/how_to_contact_us"] },
    { id: "interior", name: "משרד הפנים",
      form: "https://www.gov.il/he/pages/public-inquiries-001",
      email: "pniot@moin.gov.il",
      postal: "משרד הפנים, פניות הציבור, רח' קפלן 2, ת\"ד 7910, ירושלים",
      sources: ["https://www.gov.il/he/pages/public-inquiries-001"] },
    { id: "health", formTip: "הטופס כולל במפורש אפשרות של \"מכתב תודה\".", name: "משרד הבריאות",
      form: "https://my.health.gov.il/MyPortal/PniyotHazibur/pages/ComplaintOfferThankForm.aspx",
      email: "call.habriut@moh.health.gov.il",
      postal: "משרד הבריאות, פניות הציבור, ת\"ד 1176, ירושלים 9101002",
      sources: ["https://www.gov.il/he/service/public-inquiries-in-general-areas", "https://www.kolzchut.org.il/he/המחלקה_לפניות_הציבור_במשרד_הבריאות"] },
    { id: "transport", name: "משרד התחבורה (משרד הרישוי)",
      form: "https://www.gov.il/he/service/complaints_regarding_vehicle_registration_and_driving",
      postal: "משרד התחבורה, רח' בנק ישראל 5, בניין ג'נרי 1, ת\"ד 867, ירושלים 9100801",
      sources: [GUIDE_2024, "https://www.gov.il/he/service/complaints_regarding_vehicle_registration_and_driving"] },
    { id: "education", name: "משרד החינוך",
      form: "https://www.gov.il/he/departments/units/public-inquiries-complaints",
      email: "tluna@education.gov.il",
      postal: "האגף לפניות ולתלונות הציבור, משרד החינוך, רח' דבורה הנביאה 2, ירושלים 9100201",
      sources: [GUIDE_2024, "https://www.gov.il/he/departments/units/public-inquiries-complaints"] },
    { id: "welfare", name: "משרד הרווחה והביטחון החברתי",
      form: "https://govforms.gov.il/mw/forms/MolsaContact@molsa.gov.il",
      email: "pniot@molsa.gov.il",
      postal: "פניות הציבור, משרד הרווחה והביטחון החברתי, רח' קפלן 2, ת\"ד 915, ירושלים 9100801",
      sources: [GUIDE_2024, "https://www.gov.il/he/service/contact-the-ministry-of-labor-welfare-and-social-services"] },
    { id: "employment", name: "שירות התעסוקה הישראלי",
      form: "https://www.taasuka.gov.il/he/InfoAndPublications/Pages/Pniot.aspx",
      sources: [GUIDE_2024] },
    { id: "aliyah", name: "משרד העלייה והקליטה",
      form: "https://www.gov.il/he/service/moia-public-inquiries",
      email: "pniotzibur@moia.gov.il",
      postal: "היחידה לפניות ולתלונות הציבור, משרד העלייה והקליטה, רח' קפלן 2, ירושלים",
      sources: [GUIDE_2024, "https://www.gov.il/he/Departments/Units/moia-public-inquiries-unit"] },
    { id: "housing", name: "משרד הבינוי והשיכון",
      form: "https://www.gov.il/he/departments/units/public_inquiries_moch",
      email: "pniot@moch.gov.il",
      postal: "משרד הבינוי והשיכון, רח' קלרמון גאנו 3, ת\"ד 18110, ירושלים 9118002",
      sources: ["https://www.gov.il/he/departments/units/public_inquiries_moch", GUIDE_2024] },
    { id: "ila", name: "רשות מקרקעי ישראל",
      form: "https://www.gov.il/he/pages/faq-public-inquiries",
      postal: "רשות מקרקעי ישראל, הממונה על פניות הציבור, רח' הצבי 15, ת\"ד 36666, ירושלים 9136601",
      sources: ["https://www.gov.il/he/pages/faq-public-inquiries", GUIDE_2024] },
    { id: "justice", name: "משרד המשפטים",
      form: "https://publicinquiries.justice.gov.il/",
      postal: "משרד המשפטים, היחידה לפניות הציבור, ת\"ד 49029, ירושלים 9149001",
      sources: ["https://publicinquiries.justice.gov.il/", GUIDE_2024] },
    { id: "enforcement", name: "רשות האכיפה והגבייה (הוצאה לפועל)",
      form: "https://go.gov.il/ecapniyot",
      postal: "רשות האכיפה והגבייה, פניות הציבור, ת\"ד 34235, ירושלים 9134102",
      sources: ["https://www.gov.il/BlobFolder/generalpage/freedom_information_act/ar/info-freedom-eca-report-2022.pdf"] },
    { id: "courts", name: "הרשות השופטת (הנהלת בתי המשפט)",
      form: "https://www.gov.il/he/Departments/Units/judiciary_public_inquiries_law",
      email: "pniyot@court.gov.il",
      postal: "הנהלת בתי המשפט, פניות הציבור, רח' כנפי נשרים 22, ירושלים",
      sources: [GUIDE_2024] },
    { id: "police", formTip: "הערוץ הרשמי מיועד בעיקר לתלונות. לתודה לשוטר/ת עדיף מכתב מודפס למפקד/ת התחנה.", name: "משטרת ישראל",
      form: "https://www.gov.il/he/pages/police_public_complaints_unit",
      postal: "משטרת ישראל, מדור תלונות ציבור ארצי, המטה הארצי, שייח ג'ארח 1, ירושלים 9720045",
      sources: ["https://www.gov.il/he/pages/police_public_complaints_unit"] },
    { id: "rehab", name: "משרד הביטחון – אגף השיקום",
      form: "https://forms.mod.gov.il/PublicInquiries",
      email: "shikumn@mod.gov.il",
      postal: "אגף השיקום – פניות ציבור, בניין מרכבים, רח' ז'בוטינסקי 94, פתח תקווה",
      sources: ["https://www.mod.gov.il/Public_Inquiries/Pages/default.aspx", GUIDE_2024] },
    { id: "finance", preferEmail: true, formTip: "הטופס דורש הרשמה למערכת, לכן עדיף לשלוח במייל.", name: "משרד האוצר",
      form: "https://general.mof.gov.il/pnz/s/login/SelfRegister",
      email: "pniot@mof.gov.il",
      postal: "משרד האוצר, היחידה לפניות הציבור, רח' קפלן 1, ירושלים 9195015",
      sources: [GUIDE_2024] },
    { id: "csc", formTip: "מתאים לתודה לעובדי הנציבות עצמה. לעובד/ת במשרד ממשלתי אחר, שלחו למשרד שבו הוא או היא עובדים.", name: "נציבות שירות המדינה",
      form: "https://merkava.mrp.gov.il/pubinq/index.html",
      email: "naziv@csc.gov.il",
      postal: "נציבות שירות המדינה, רח' קפלן 3, ת\"ד 34076, ירושלים 91340",
      sources: [GUIDE_2024] }
  ]},
  { group: "שירותים ציבוריים", items: [
    { id: "post", name: "דואר ישראל",
      site: "https://www.israelpost.co.il",
      form: "https://doar.israelpost.co.il/contactus",
      sources: ["https://www.israelpost.co.il/"] },
    { id: "clalit", formTip: "הטופס מבקש הזדהות. ערוצי פניות הציבור של כללית מקבלים גם מחמאות.", name: "שירותי בריאות כללית",
      site: "https://www.clalit.co.il",
      form: "https://e-services.clalit.co.il/OnlineWeb/NVGG/ClalitPublicInquiries/PublicInquiries",
      sources: ["https://www.clalit.co.il/he/info/Pages/list_of_aumbdsmn.aspx"] },
    { id: "maccabi", formTip: "בטופס בחרו בסוג הפנייה \"תודות\".", name: "מכבי שירותי בריאות",
      site: "https://www.maccabi4u.co.il",
      form: "https://www.maccabi4u.co.il/forms/public-appeal/",
      postal: "מכבי שירותי בריאות, נציבות פניות הציבור, ת\"ד 50493, תל אביב 68125",
      sources: ["https://www.maccabi4u.co.il/forms/public-appeal/"] },
    { id: "meuhedet", name: "קופת חולים מאוחדת",
      site: "https://www.meuhedet.co.il",
      form: "https://www.meuhedet.co.il/%D7%9E%D7%99%D7%93%D7%A2-%D7%9C%D7%9C%D7%A7%D7%95%D7%97/%D7%98%D7%95%D7%A4%D7%A1-%D7%A4%D7%A0%D7%99%D7%95%D7%AA-%D7%94%D7%A6%D7%99%D7%91%D7%95%D7%A8/",
      postal: "קופת חולים מאוחדת, פניות הציבור, רח' אבן גבירול 124, תל אביב 6203854",
      sources: ["https://www.meuhedet.co.il/%D7%9E%D7%99%D7%93%D7%A2-%D7%9C%D7%9C%D7%A7%D7%95%D7%97/%D7%A4%D7%A0%D7%99%D7%95%D7%AA-%D7%94%D7%A6%D7%99%D7%91%D7%95%D7%A8/"] },
    { id: "leumit", name: "לאומית שירותי בריאות",
      site: "https://www.leumit.co.il",
      form: "https://www.leumit.co.il/contact-us/public-appeals/",
      postal: "לכבוד פניות הציבור, לאומית שירותי בריאות, רח' שפרינצק 23, תל אביב",
      sources: ["https://www.leumit.co.il/contact-us/public-appeals/"] },
    { id: "rail", name: "רכבת ישראל",
      form: "https://www.rail.co.il/support/pages/publicap.aspx",
      email: "pniyotz@rail.co.il",
      postal: "רכבת ישראל, מחלקת פניות הציבור, רח' יוספטל 1, ת\"ד 757, לוד 7136801",
      sources: ["https://web-umbraco.rail.co.il/media/c2nnfhdl/%D7%93%D7%95%D7%97-%D7%97%D7%95%D7%A7-%D7%97%D7%95%D7%A4%D7%A9-%D7%94%D7%9E%D7%99%D7%93%D7%A2-%D7%9C%D7%A9%D7%A0%D7%AA-2025.pdf"] },
    { id: "iec", preferEmail: true, formTip: "הטופס מיועד לתלונות, לכן עדיף לשלוח במייל ולציין \"מחמאה\" בשורת הנושא.", name: "חברת החשמל לישראל",
      form: "https://www.iec.co.il/content/ombudsman/pages/filingcomplaint",
      email: "TlunotHatsibur@iec.co.il",
      postal: "חברת החשמל, פניות הציבור, ת\"ד 25, תל אביב 6100001",
      sources: ["https://ieccontent.iec.co.il/media/kvapzeu0/amana.pdf"] },
    { id: "mda", formTip: "בטופס בחרו בנושא \"תודות, מחמאות\".", name: "מגן דוד אדום",
      form: "https://www.mdais.org/contactus",
      email: "mdainquiries@mda.org.il",
      postal: "מגן דוד אדום בישראל, רח' הפלדה 5, אור יהודה 6021805",
      sources: ["https://www.mdais.org/contactus"] },
    { id: "municipality", name: "עירייה / מועצה מקומית", askName: true }
  ]},
  { group: "אחר", items: [
    { id: "other", name: "ארגון אחר", askName: true }
  ]}
];
